#ifndef AST_OPERATOR_H
#define AST_OPERATOR_H

enum class Operator {
	UNARY_MINUS,
	MULTIPLY, DIVIDE, MOD, PLUS, MINUS, 
	LESS, LESS_OR_EQUAL, GREATER, GREATER_OR_EQUAL, EQUAL, NOT_EQUAL,
	NOT,
	AND, OR
};

#endif
